import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const { chromium } = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
try {
  const page = await browser.newPage({ viewport: { width: 1500, height: 1050 }, colorScheme: 'light' });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:4180/');
  const select = page.getByRole('combobox', { name: 'Darstellung der App' });
  await select.waitFor(); assert.equal(await select.inputValue(), 'system');
  const before = await page.locator('#yaml').textContent();
  const blocklyTheme = await page.locator('#theme').inputValue();
  const appearance = () => page.locator('html').getAttribute('data-appearance');
  assert.equal(await appearance(), 'light');
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.waitForFunction(() => document.documentElement.dataset.appearance === 'dark');
  await select.selectOption('light'); await page.emulateMedia({ colorScheme: 'light' }); await page.emulateMedia({ colorScheme: 'dark' });
  assert.equal(await appearance(), 'light');
  await select.selectOption('dark'); await page.reload(); await select.waitFor();
  assert.equal(await select.inputValue(), 'dark');
  await page.emulateMedia({ colorScheme: 'light' }); assert.equal(await appearance(), 'dark');
  assert.equal(await page.locator('#theme').inputValue(), blocklyTheme);
  assert.equal(await page.locator('#yaml').textContent(), before);
  assert.ok((await page.locator('footer .blockly-attribution img').getAttribute('src')).endsWith('-black.svg'));
  const colour = selector => page.locator(selector).evaluate(e => ({ background: getComputedStyle(e).backgroundColor, text: getComputedStyle(e).color }));
  assert.deepEqual(await colour('.project-bar'), { background: 'rgb(29, 42, 51)', text: 'rgb(227, 236, 233)' });
  await page.getByRole('button', { name: 'Über & Lizenzen' }).click();
  assert.equal((await colour('#about-dialog')).background, 'rgb(29, 42, 51)');
  await page.screenshot({ path: 'artifacts/appearance-about-dark.png', fullPage: true });
  await page.locator('#about-dialog').getByRole('button', { name: 'Schließen' }).click();
  await page.locator('#custom-editor-open').click();
  assert.equal((await colour('#custom-editor')).background, 'rgb(29, 42, 51)');
  await page.screenshot({ path: 'artifacts/appearance-custom-dark.png', fullPage: true });
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Blocks im Arbeitsbereich suchen' }).click();
  assert.equal((await colour('.blockly-ws-search')).background, 'rgb(38, 60, 70)');
  await page.keyboard.press('Escape');
  await select.selectOption('system'); assert.equal(await appearance(), 'light');
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.waitForFunction(() => document.documentElement.dataset.appearance === 'dark');
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: 'artifacts/appearance-mobile-dark.png', fullPage: true });
  await select.selectOption('light');
  assert.ok((await page.locator('footer .blockly-attribution img').getAttribute('src')).endsWith('-white.svg'));
  assert.equal(await page.locator('#yaml').textContent(), before);
  assert.deepEqual(errors, []);
  // Invalid storage and unavailable storage both fall back safely to System.
  await page.evaluate(() => localStorage.setItem('ugso-blocks-for-ha-appearance', 'unknown'));
  await page.reload(); await select.waitFor(); assert.equal(await select.inputValue(), 'system');
  const isolated = await browser.newContext({ colorScheme: 'dark' });
  await isolated.addInitScript(() => { Object.defineProperty(window, 'localStorage', { get() { throw new Error('Blocked'); } }); });
  const blocked = await isolated.newPage(); await blocked.goto('http://127.0.0.1:4180/');
  await blocked.getByRole('combobox', { name: 'Darstellung der App' }).selectOption('light');
  assert.equal(await blocked.locator('html').getAttribute('data-appearance'), 'light'); await isolated.close();
  console.log('App Light/Dark/System: live OS changes, overrides, reload, blocked/invalid storage, independent Blockly palette, unchanged YAML, dialogs, search, badges and mobile layout verified.');
} finally { await browser.close(); }
