import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { readFile, mkdir } from 'node:fs/promises';
import { fromYaml } from '../src/model.js';
const { chromium } = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
try {
  const context = await browser.newContext({ viewport: { width: 1500, height: 1050 }, permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('dialog', dialog => dialog.accept());
  await page.goto('http://127.0.0.1:4180/');
  await page.locator('#save').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#valid-badge').textContent(), 'Gültig');
  assert.match(await page.locator('#yaml').textContent(), /binary_sensor.flur_bewegung/);
  await page.locator('#name').fill('Meine Küchenbeleuchtung');
  await page.locator('#copy').click();
  const copied = await page.evaluate(() => navigator.clipboard.readText());
  assert.equal(fromYaml(copied).alias, 'Meine Küchenbeleuchtung');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#save').click();
  const download = await downloadPromise;
  assert.equal(download.suggestedFilename(), 'meine-kuchenbeleuchtung.yaml');
  const saved = await readFile(await download.path(), 'utf8');
  assert.equal(fromYaml(saved).alias, 'Meine Küchenbeleuchtung');
  await page.locator('#example').selectOption('battery');
  await page.locator('#load-example').click();
  assert.match(await page.locator('#yaml').textContent(), /below: 20/);
  await page.locator('#yaml-file').setInputFiles({ name: 'licht.yaml', mimeType: 'text/yaml', buffer: Buffer.from(saved) });
  await page.waitForFunction(() => document.getElementById('name').value === 'Meine Küchenbeleuchtung');
  assert.match(await page.locator('#yaml').textContent(), /light.turn_on/);
  const before = await page.locator('#yaml').textContent();
  await page.locator('#yaml-file').setInputFiles({ name: 'unbekannt.yaml', mimeType: 'text/yaml', buffer: Buffer.from(saved + '\nvariables:\n  verborgen: true\n') });
  await page.waitForFunction(() => document.getElementById('toast').textContent.includes('nicht unterstützt'));
  assert.equal(await page.locator('#yaml').textContent(), before);
  await page.reload();
  assert.equal(await page.locator('#name').inputValue(), 'Meine Küchenbeleuchtung');
  await page.locator('#format').selectOption('list');
  assert.match(await page.locator('#yaml').textContent(), /^- /);
  assert.equal(fromYaml(await page.locator('#yaml').textContent()).alias, 'Meine Küchenbeleuchtung');
  await page.locator('#about').click();
  assert.match(await page.locator('#about-dialog').textContent(), /Blockly/);
  await page.getByRole('button', { name: 'Schließen', exact: true }).click();
  assert.equal((await page.request.get('http://127.0.0.1:4180/licenses/BLOCKLY-LICENSE.txt')).status(), 200);
  await mkdir('artifacts', { recursive: true });
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
  assert.deepEqual(errors, []);
  console.log('Browser: Blocks, clipboard, YAML download/open, rejected import, reload, list format, licenses and mobile width verified.');
} finally { await browser.close(); }
