import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, readFile } from 'node:fs/promises';
import { customExample } from '../src/custom-example.js';
import { readPackageZip } from '../src/custom-packages.js';
const { chromium } = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
try {
  const page = await browser.newPage({ viewport: { width: 1500, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] }), errors = [];
  page.on('pageerror', e => errors.push(e.message)); page.on('dialog', dialog => dialog.accept());
  await page.route('**/api/ha/entities', route => route.fulfill({ contentType: 'application/json', body: '{"entities":[]}' }));
  await page.goto('http://127.0.0.1:4180/');
  await page.locator('#custom-editor-open').waitFor(); const before = await page.locator('#yaml').textContent();
  await page.evaluate(async () => { const url = performance.getEntriesByType('resource').find(e => new URL(e.name).pathname === '/src/blocks.js').name; const { Blockly } = await import(url); globalThis.mainTestWorkspace = Blockly.getMainWorkspace(); });
  await page.locator('#custom-editor-open').click();
  await page.waitForFunction(() => !document.querySelector('#custom-apply').disabled);
  const size = await page.locator('#custom-editor').boundingBox(); assert.ok(Math.abs(size.width - 1500 * .95) < 2); assert.ok(Math.abs(size.height - 1000 * .95) < 2);
  await page.locator('#custom-example').click();
  await page.waitForFunction(() => document.querySelector('#custom-code').value.includes('ugso_sensor_tools'));
  await mkdir('artifacts', { recursive: true }); await page.screenshot({ path: 'artifacts/custom-editor.png', fullPage: true });
  await page.locator('#custom-copy').click(); assert.equal(JSON.parse(await page.evaluate(() => navigator.clipboard.readText())).id, customExample.id);
  const zipPromise = page.waitForEvent('download'); await page.locator('#custom-export-zip').click(); const zip = await zipPromise;
  assert.equal(zip.suggestedFilename(), 'ugso_sensor_tools-1.0.0.zip'); assert.deepEqual(await readPackageZip(new Uint8Array(await readFile(await zip.path()))), customExample);
  await page.locator('#custom-apply').click(); await page.locator('#custom-editor').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('#yaml').textContent(), before);
  await page.locator('.blocklyToolboxCategory').filter({ hasText: /^Benutzerdefiniert$/ }).click();
  await page.waitForFunction(() => [...document.querySelectorAll('.blocklyFlyout')].some(el => el.textContent.replace(/\s/g, ' ').includes('Sensorwert als Zahl') && el.getBoundingClientRect().width > 0));
  await page.evaluate(async () => {
    const ws = globalThis.mainTestWorkspace;
    const action = ws.newBlock('ugso_custom_ugso_sensor_tools__light_on'); action.setFieldValue(75, 'BRIGHTNESS'); action.initSvg(); action.render(); ws.getBlocksByType('ugso_switch_action')[0].nextConnection.connect(action.previousConnection); ws.getToolbox().clearSelection(); ws.zoomToFit();
  });
  await page.waitForFunction(() => document.querySelector('#yaml').textContent.includes('brightness_pct: 75'));
  const yaml = await page.locator('#yaml').textContent();
  await page.locator('summary').filter({ hasText: 'Projekt & Beschreibung' }).click();
  const projectPromise = page.waitForEvent('download'); await page.locator('#project-save').click(); const project = await projectPromise; const projectBytes = await readFile(await project.path()); const json = JSON.parse(projectBytes);
  assert.equal(json.version, 3); assert.deepEqual(json.packages, [customExample]);
  await page.evaluate(() => localStorage.clear()); await page.reload();
  await page.locator('#project-file').setInputFiles({ name: 'portable.blocks.json', mimeType: 'application/json', buffer: projectBytes });
  await page.waitForFunction(() => document.querySelector('#yaml').textContent.includes('brightness_pct: 75'));
  assert.equal(await page.locator('#yaml').textContent(), yaml);
  await page.reload(); await page.waitForFunction(() => document.querySelector('#yaml').textContent.includes('brightness_pct: 75'));
  await page.locator('#custom-editor-open').click();
  await page.locator('#custom-editor summary').filter({ hasText: 'JSON-Code oder ZIP importieren' }).click();
  await page.locator('#custom-import-code').fill(JSON.stringify({ ...customExample, version: '1.0.1' }));
  await page.waitForFunction(() => document.querySelector('#custom-apply').disabled);
  await page.locator('#custom-import').click(); await page.waitForFunction(() => !document.querySelector('#custom-apply').disabled);
  await page.locator('#custom-apply').click(); assert.match(await page.locator('#custom-status').textContent(), /bereits/); assert.equal(await page.locator('#yaml').textContent(), yaml);
  await page.locator('#custom-cancel').click();
  await page.locator('#custom-editor-open').click();
  await page.locator('#custom-zip-file').setInputFiles({ name: 'sample.zip', mimeType: 'application/zip', buffer: await readFile(await zip.path()) });
  await page.waitForFunction(() => document.querySelector('#custom-id').value === 'ugso_sensor_tools' && !document.querySelector('#custom-apply').disabled);
  await page.locator('#custom-apply').click(); await page.locator('#custom-editor').waitFor({ state: 'hidden' });
  const bad = structuredClone(json); bad.packages[0].id = 'should_rollback'; bad.workspace.blocks.blocks[0].type = 'missing_block';
  await page.locator('#project-file').setInputFiles({ name: 'bad.blocks.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(bad)) });
  await page.locator('#toast').filter({ hasText: 'Blockpaket fehlt' }).waitFor(); assert.equal(await page.locator('#yaml').textContent(), yaml);
  assert.equal(await page.evaluate(() => localStorage.getItem('ugso-ha-block-packages-v1').includes('should_rollback')), false);
  await page.setViewportSize({ width: 390, height: 844 }); await page.locator('#custom-editor-open').click();
  await page.waitForFunction(() => !document.querySelector('#custom-apply').disabled);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.querySelector('#custom-editor').scrollWidth <= document.querySelector('#custom-editor').clientWidth), true);
  await page.screenshot({ path: 'artifacts/custom-editor-mobile.png', fullPage: true }); await page.keyboard.press('Escape');
  assert.deepEqual(errors, []);
  console.log('95% editor, live Blockly preview, copied JSON/ZIP equality, custom toolbox, HA output, portable project/reload, collisions/rollback and mobile layout verified.');
} finally { await browser.close(); }
