name: MQTT-Client
version: "0.1.2"
slug: mqtt_client
description: Send selected Home Assistant states to an external MQTT broker such as ioBroker
url: https://github.com/rockbaer2007/ugso-ha-mqtt-addons/tree/master/mqtt_client
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
homeassistant_api: true
ingress: true
ingress_port: 8099
panel_icon: mdi:lan-connect
panel_title: MQTT-Client
options:
  broker_host: ""
  broker_port: 1883
  username: ""
  password: ""
  tls: false
  client_id: ugso-ha-mqtt-client
  topic_prefix: ha_external
  poll_interval: 5
  entities: []
  entity_attributes: []
  command_entities: []
schema:
  broker_host: str
  broker_port: port
  username: str
  password: password
  tls: bool
  client_id: str
  topic_prefix: str
  poll_interval: int(1,300)
  entities:
    - str
  entity_attributes:
    - str
  command_entities:
    - str
