name: HA Grafik Visual Studio
version: "0.1.98"
slug: ha_grafik_visual_studio
description: Experimentelles Grundgerüst für grafische Home-Assistant-Visualisierungen
stage: experimental
url: https://github.com/rockbaer2007/ugso-ha-mqtt-addons/tree/master/ha_grafik_visual_studio
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8098
homeassistant_api: true
panel_icon: mdi:vector-square-edit
panel_title: HA Grafik Visual Studio
map:
  - type: homeassistant_config
    read_only: false
    path: /homeassistant
