// HA expressions generated by UGSo; ioBroker's conversion category is a UI reference.
const colour = '#9463a6';
const input = (name, check) => ({ type: 'input_value', name, check });
const dropdown = (name, options) => ({ type: 'field_dropdown', name, options });
const outputs = type => [type, 'Value'];
export const dateFormats = [
  ['Datumswert', 'date'], ['ISO mit Zeitzone', 'iso'], ['Uhrzeit HH:mm', '%H:%M'], ['Uhrzeit HH:mm:ss', '%H:%M:%S'],
  ['Datum JJJJ-MM-TT', '%Y-%m-%d'], ['Datum TT.MM.JJJJ', '%d.%m.%Y'], ['Datum und Uhrzeit', '%d.%m.%Y %H:%M:%S'],
  ['Unix-Sekunden', 'unix'], ['Unix-Millisekunden', 'unix_ms'], ['Jahr', 'year'], ['Monat', 'month'], ['Tag', 'day'],
  ['Stunde', 'hour'], ['Minute', 'minute'], ['Sekunde', 'second'], ['Millisekunde', 'ms'], ['Wochentag (Mo=1)', 'weekday'],
  ['ISO-Kalenderwoche', 'week'], ['Sekunden seit Mitternacht', 'day_seconds'], ['Minuten seit Mitternacht', 'day_minutes'], ['Eigenes Format', 'custom']
];
const numericFormats = new Set(['unix', 'unix_ms', 'year', 'month', 'day', 'hour', 'minute', 'second', 'ms', 'weekday', 'week', 'day_seconds', 'day_minutes']);
export const conversionDefinitions = [
  { type: 'ugso_convert_number', message0: 'Nach Zahl %1', args0: [input('VALUE', 'Value')], output: outputs('RuntimeNumber'), colour, tooltip: 'HA float(): vollständiger Zahlenwert mit Dezimalpunkt. Kein parseFloat-Präfix und kein stiller Ersatzwert. Laufzeitzahl für Vergleiche, Variablen und Zeitrechnung; kein fester Auslöser-Grenzwert.' },
  { type: 'ugso_convert_boolean', message0: 'Nach Logikwert %1', args0: [input('VALUE', 'Value')], output: outputs('Boolean'), colour, tooltip: 'HA bool(): wahr/falsch, true/false, on/off, yes/no, 1/0. Nicht erkannte Werte erzeugen einen Template-Fehler.' },
  { type: 'ugso_convert_string', message0: 'Nach String %1', args0: [input('VALUE', 'Value')], output: outputs('String'), colour, tooltip: 'Jinja-Textdarstellung, keine JSON-Serialisierung. Boolean wird beispielsweise True/False.' },
  { type: 'ugso_convert_type', message0: 'Typ von %1', args0: [input('VALUE', 'Value')], output: outputs('String'), colour, tooltip: 'HA typeof(): Python-Typnamen wie str, int, float, bool, dict, list oder NoneType. HA ab 2023.4.' },
  { type: 'ugso_convert_datetime', message0: 'Nach Datum/Zeit %1 Eingabe %2', args0: [input('VALUE', 'Value'), dropdown('UNIT', [['ISO-Text', 'iso'], ['Unix-Sekunden', 'seconds'], ['Unix-Millisekunden', 'milliseconds']])], output: outputs('Time'), colour, tooltip: 'ISO-Text möglichst mit Z oder Zeitzonenoffset. Unix-Einheit ausdrücklich wählen. Ergebnis in HA-Ortszeit; ungültige Eingaben erzeugen einen Template-Fehler.' },
  { type: 'ugso_convert_date_format', message0: 'Datum/Zeit %1 nach %2', args0: [input('VALUE', 'Time'), dropdown('FORMAT', dateFormats)], output: outputs('Time'), colour, extensions: ['ugso_conversion_format'] },
  { type: 'ugso_convert_duration', message0: 'Zeitdifferenz %1 Eingabe %2 nach %3', args0: [input('VALUE', ['Number', 'RuntimeNumber']), dropdown('UNIT', [['Millisekunden', 'milliseconds'], ['Sekunden', 'seconds']]), dropdown('FORMAT', [['hh:mm:ss', 'hms'], ['hh:mm', 'hm'], ['mm:ss', 'ms']])], output: outputs('String'), colour, tooltip: 'Dauer als Zahl, standardmäßig Millisekunden wie in ioBroker. Ganze Sekunden; Restbruchteile werden abgeschnitten. Stunden/Minuten dürfen über 24/60 liegen; Vorzeichen bleibt erhalten.' },
  { type: 'ugso_convert_from_json', message0: 'JSON nach Wert %1', args0: [input('VALUE', 'String')], output: 'Value', colour, tooltip: 'HA from_json: Objekt, Liste oder JSON-Einzelwert. Ungültiges JSON erzeugt einen Fehler, kein leeres Ersatzobjekt.' },
  { type: 'ugso_convert_to_json', message0: 'Wert nach JSON %1 formatieren %2', args0: [input('VALUE', 'Value'), { type: 'field_checkbox', name: 'PRETTY', checked: false }], output: outputs('String'), colour, tooltip: 'HA to_json mit optionaler Einrückung. Datumswerte erst nach ISO-Text oder Unix-Zahl konvertieren.' }
];
export function installConversionShape(Blockly) {
  Blockly.Extensions.register('ugso_conversion_format', function () {
    const update = format => {
      if (format === 'custom' && !this.getInput('PATTERN')) this.appendDummyInput('PATTERN').appendField('Format').appendField(new Blockly.FieldTextInput('%d.%m.%Y %H:%M'), 'PATTERN');
      if (format !== 'custom' && this.getInput('PATTERN')) this.removeInput('PATTERN');
      this.outputConnection.setCheck(outputs(format === 'date' ? 'Time' : numericFormats.has(format) ? 'RuntimeNumber' : 'String'));
    };
    this.getField('FORMAT').setValidator(format => { update(format); return format; });
    update(this.getFieldValue('FORMAT'));
    this.setInputsInline(true);
    this.setTooltip('Die Auswahl bestimmt den Anschluss: Datumswert, Laufzeitzahl oder Text. Eigenes Format nutzt Python strftime (%Y, %m, %d, %H, %M, %S), keine ioBroker-Formatcodes.');
  });
}
export function conversionExpression(block, child) {
  const val = child('VALUE'), field = name => block.getFieldValue(name);
  switch (block.type) {
    case 'ugso_convert_number': return `float(${val})`;
    case 'ugso_convert_boolean': return `bool(${val})`;
    case 'ugso_convert_string': return `(${val} | string)`;
    case 'ugso_convert_type': return `typeof(${val})`;
    case 'ugso_convert_datetime': return `as_local(as_datetime(${field('UNIT') === 'iso' ? val : `float(${val})${field('UNIT') === 'milliseconds' ? ' / 1000' : ''}`}))`;
    case 'ugso_convert_from_json': return `(${val} | from_json)`;
    case 'ugso_convert_to_json': return `(${val} | to_json(pretty_print=${field('PRETTY') === 'TRUE' ? 'true' : 'false'}))`;
    case 'ugso_convert_date_format': {
      const date = `(${val})`, format = field('FORMAT');
      if (format === 'date') return date;
      if (format === 'iso') return `${date}.isoformat()`;
      if (format === 'unix' || format === 'unix_ms') return `(as_timestamp(${date})${format === 'unix_ms' ? ' * 1000' : ''})`;
      if (['year', 'month', 'day', 'hour', 'minute', 'second'].includes(format)) return `${date}.${format}`;
      if (format === 'ms') return `(${date}.microsecond // 1000)`;
      if (format === 'weekday') return `${date}.isoweekday()`;
      if (format === 'week') return `int(${date}.strftime('%V'))`;
      if (format === 'day_seconds') return `(${date}.hour * 3600 + ${date}.minute * 60 + ${date}.second)`;
      if (format === 'day_minutes') return `(${date}.hour * 60 + ${date}.minute)`;
      const pattern = format === 'custom' ? field('PATTERN') : format;
      if (!pattern?.trim()) throw new Error('Datumsformat fehlt.');
      return `${date}.strftime(${JSON.stringify(pattern)})`;
    }
    case 'ugso_convert_duration': {
      const raw = `float(${val})`, seconds = `((${raw} | abs)${field('UNIT') === 'milliseconds' ? ' / 1000' : ''} | int)`;
      const parts = field('FORMAT') === 'ms' ? [`${seconds} // 60`, `${seconds} % 60`] : [`${seconds} // 3600`, `(${seconds} // 60) % 60`, ...(field('FORMAT') === 'hms' ? [`${seconds} % 60`] : [])];
      return `((('-' if ${raw} < 0 else '') ~ ${JSON.stringify(parts.map(() => '%02d').join(':'))}) % (${parts.join(', ')}))`;
    }
    default: throw new Error('Unbekannte Konvertierung.');
  }
}
