import { dropdownCount } from "../dropdown.js";
const color = (label, key) => ({ label, key, type: "color", optionalColor: true });
const range = (label, key, min = 0, max = 50) => ({ label, key, type: "range", min, max });
const count = (label, key, max) => ({ label, key, type: "number", min: 0, max, refreshProperties: true });
const shadow = (prefix, heading) => [range(heading + " · X-Versatz", prefix + "X", -50), range(heading + " · Y-Versatz", prefix + "Y", -50), range(heading + " · Unschärfe", prefix + "Blur"), range(heading + " · Ausdehnung", prefix + "Spread", -50), color(heading + " · Schattenfarbe", prefix + "Color")];
export function dropdownEntryGroups(widget) {
  return [
    ...(widget.useCustomOptions ? Array.from({ length: dropdownCount(widget.countCustomOptions) }, (_, i) => ({ id: `dropdown-option-${i + 1}`, label: `Option [${i + 1}]`, defaultEnabled: true, fields: [{ label: "Wert", key: `optionValue${i + 1}` }, { label: "Text", key: `optionText${i + 1}` }] })) : []),
    ...Array.from({ length: dropdownCount(widget.countBgConditions, 20) }, (_, i) => ({ id: `dropdown-condition-${i + 1}`, label: `Hintergrundbedingung [${i + 1}]`, defaultEnabled: true, fields: [{ label: "Vergleichsoperator", key: `bgOperator${i + 1}`, type: "select", options: [["===", "Gleich"], ["!=", "Ungleich"], [">", "Größer"], ["<", "Kleiner"], [">=", "Größer gleich"], ["<=", "Kleiner gleich"]].map(([value, label]) => ({ value, label })) }, { label: "Vergleichswert", key: `bgValue${i + 1}` }, color("Hintergrund", `bgColor${i + 1}`)] })),
  ];
}
export const dropdownDefinition = {
  type: "dropdown", label: "Dropdown", icon: "▾", searchTerms: ["Auswahlliste", "Select"],
  defaults: { width: 300, height: 50, entityId: "", state: "", dropdownTitle: "", useCustomOptions: false, showValue: true, showText: true, readOnly: false, countCustomOptions: 0, bgEntityId: "", countBgConditions: 0, dropdownFontSize: 16, dropdownTextColor: "#FFFFFF", dropdownBackgroundColor: "#323232", dropdownHighlightColor: "#8FA455", dropdownBorderColor: "#646464", dropdownBorderWidth: 1, dropdownBorderRadius: 4, titleFontSize: 12, titleColor: "#B4B4B4", titleBgFromCondition: false, titlePaddingTop: 2, titlePaddingBottom: 4, titlePaddingLeft: 0, titlePaddingRight: 0, shadowX: 2, shadowY: 2, shadowBlur: 4, shadowSpread: 0, shadowColor: "#00000080", widgetShadowX: 0, widgetShadowY: 0, widgetShadowBlur: 0, widgetShadowSpread: 0, widgetShadowColor: "#00000080", backgroundColor: "transparent", borderWidth: 0, radius: 0, padding: 0, cssOverflowX: "visible", cssOverflowY: "visible" },
  propertyGroups: [
    { label: "Allgemein", fields: [{ label: "Home-Assistant-Entität", key: "entityId" }, { label: "Titel", key: "dropdownTitle" }, { label: "Eigene Optionen verwenden", key: "useCustomOptions", type: "checkbox", refreshProperties: true }, { label: "Wert anzeigen", key: "showValue", type: "checkbox" }, { label: "Text anzeigen", key: "showText", type: "checkbox" }, { label: "Schreibgeschützt", key: "readOnly", type: "checkbox" }, { label: "Vorschau-/Testzustand", key: "state" }] },
    { label: "Eigene Optionen", fields: [{ ...count("Anzahl Optionen", "countCustomOptions", 200), showWhen: { key: "useCustomOptions", value: true } }] },
    { label: "Hintergrundfarb-Bedingungen", fields: [{ label: "Hintergrund-Entität (optional)", key: "bgEntityId" }, count("Anzahl der Bedingungen", "countBgConditions", 20)] },
    { label: "CSS Dropdown", css: true, defaultEnabled: true, fields: [{ label: "Vom Widget", key: "dropdownFromWidget", type: "widget", widgetType: "dropdown" }, range("Schriftgröße (px)", "dropdownFontSize", 8, 100), color("Textfarbe", "dropdownTextColor"), color("Hintergrund", "dropdownBackgroundColor"), color("Hervorhebungsfarbe", "dropdownHighlightColor"), color("Randfarbe", "dropdownBorderColor"), range("Rahmenbreite (px)", "dropdownBorderWidth", 0, 20), range("Rahmenradius (px)", "dropdownBorderRadius", 0, 100), range("Titel Schriftgröße (px)", "titleFontSize", 8, 100), color("Titelfarbe", "titleColor"), { label: "Hintergrundbedingung auf Titel anwenden", key: "titleBgFromCondition", type: "checkbox" }, ...["Top", "Bottom", "Left", "Right"].map((key, i) => range(["Titel Abstand oben", "Titel Abstand unten", "Titel Abstand links", "Titel Abstand rechts"][i], "titlePadding" + key, 0, 100)), ...shadow("shadow", "Dropdown-Schatten"), ...shadow("widgetShadow", "Widget-Schatten")] },
    { label: "Größe und Position", fields: [{ label: "Breite (px)", key: "width", type: "number", min: 32 }, { label: "Höhe (px)", key: "height", type: "number", min: 24 }, { label: "X (px)", key: "x", type: "number" }, { label: "Y (px)", key: "y", type: "number" }] },
  ],
};
