import { registerWidgetSet } from "../widget-registry.js";
const number = (label, key, min, max) => ({ label, key, type: "number", ...(["ringCount", "levelCount"].includes(key) ? { refreshProperties: true } : {}), ...(min == null ? {} : { min }), ...(max == null ? {} : { max }) });
const check = (label, key) => ({ label, key, type: "checkbox" });
const color = (label, key) => ({ label, key, type: "color", optionalColor: true });
const select = (label, key, entries) => ({ label, key, type: "select", options: entries.map(([value, label]) => ({ value, label })) });
const orientations = [["horizontal", "Horizontal"], ["vertical", "Vertikal"]];
const common = [
  { label: "Allgemein", fields: [{ label: "Home-Assistant-Entität", key: "entityId" }, number("Vorschauwert", "state"), number("Mindestwert", "minValue"), number("Maximalwert", "maxValue"), { label: "Einheit", key: "unit" }, number("Nachkommastellen", "digits", 0, 6), check("Wert anzeigen", "showValue"), { label: "Bezeichnung", key: "label" }, number("Anzahl Farbstufen", "levelCount", 1, 10)] },
  { label: "CSS Messinstrument", css: true, defaultEnabled: true, fields: [color("Aktive Farbe", "activeColor"), color("Spurfarbe", "trackColor"), color("Skalenfarbe", "scaleColor"), color("Zeigerfarbe", "needleColor"), color("Wertfarbe", "valueColor"), number("Wertgröße (px)", "valueSize", 8, 48), number("Spurbreite (px)", "trackWidth", 1, 30), check("Enden abrunden", "roundedCaps")] },
  { label: "Größe und Position", fields: [number("Breite (px)", "width", 32), number("Höhe (px)", "height", 32), number("X (px)", "x"), number("Y (px)", "y")] },
];
common[1].id = "gauge-style";
const specs = [
  ["color", "Farbmesser", "◴", { sweepAngle: 180 }, [check("Min./Max. anzeigen", "showMinMax"), number("Bogenwinkel (°)", "sweepAngle", 30, 360)]],
  ["water", "Wasserstand", "≈", {}, [check("Wellen animieren", "waveAnimation"), number("Wellenhöhe", "waveAmplitude", 0, 15), number("Wellendauer (s)", "waveDuration", .5, 30)]],
  ["battery", "Batterie", "▰", { width: 240, height: 140 }, [select("Orientierung", "orientation", orientations), number("Batteriezellen", "cells", 1, 20), { label: "Ladezustand-Entität", key: "chargingEntityId" }, check("Ladevorschau", "charging"), color("Ladesymbolfarbe", "chargingColor")]],
  ["arc", "Bogenmesser", "◔", {}, [number("Bogenwinkel (°)", "sweepAngle", 30, 360), number("Drehung (°)", "rotation", -360, 360), number("Segmente", "segments", 0, 100), number("Segmentabstand (°)", "segmentGap", 0, 10), check("Von Null aus füllen", "fromZero"), check("Min./Max. anzeigen", "showMinMax"), { label: "Zielwert-Entität", key: "targetEntityId" }, number("Zielwert (Vorschau)", "targetValue"), check("Zielmarkierung anzeigen", "showTarget"), color("Zielfarbe", "targetColor")]],
  ["compass", "Kompass", "✥", { maxValue: 360, state: 45, unit: "°", levelCount: 1 }, [number("Nordversatz (°)", "northOffset", -360, 360), check("Richtung umkehren", "invertDirection"), check("Skala mitdrehen", "rotateDial"), check("Zwischenrichtungen anzeigen", "showIntercardinal"), select("Kompasswert", "compassFormat", [["both", "Grad und Richtung"], ["degrees", "Grad"], ["direction", "Richtung"]]), { label: "Geschwindigkeits-Entität", key: "speedEntityId" }, number("Geschwindigkeit (Vorschau)", "speedValue"), { label: "Geschwindigkeitseinheit", key: "speedUnit" }]],
  ["linear", "Linearmesser", "━", { width: 280, height: 140 }, [select("Orientierung", "orientation", orientations), select("Darstellung", "displayMode", [["bar", "Balken"], ["pointer", "Zeiger"]]), check("Von Null aus füllen", "fromZero"), check("Skala anzeigen", "showScale"), number("Hauptintervalle", "majorTicks", 1, 20), number("Unterteilungen", "minorTicks", 0, 10), { label: "Zielwert-Entität", key: "targetEntityId" }, number("Zielwert (Vorschau)", "targetValue"), check("Zielmarkierung anzeigen", "showTarget"), color("Zielfarbe", "targetColor")]],
  ["radial", "Rundinstrument", "◴", { sweepAngle: 270 }, [number("Bogenwinkel (°)", "sweepAngle", 30, 360), number("Drehung (°)", "rotation", -360, 360), check("Skala anzeigen", "showScale"), number("Hauptintervalle", "majorTicks", 1, 20), number("Unterteilungen", "minorTicks", 0, 10), select("Zeigertyp", "needleType", [["arrow", "Pfeil"], ["line", "Linie"], ["triangle", "Dreieck"]]), select("Instrumentenrahmen", "bezel", [["none", "Keiner"], ["thin", "Dünn"], ["metal", "Metall"]])]],
  ["rings", "Ringe", "◎", { ringCount: 3, sweepAngle: 270 }, [number("Anzahl Ringe", "ringCount", 1, 8), number("Bogenwinkel (°)", "sweepAngle", 30, 360), number("Drehung (°)", "rotation", -360, 360), select("Legende", "legend", [["bottom", "Unten"], ["side", "Seitlich"], ["none", "Keine"]]), number("Ringabstand (px)", "ringGap", 1, 10)]],
  ["tank", "Tank", "▱", {}, [select("Tankform", "tankShape", [["cylinder", "Zylinder"], ["rect", "Rechteck"], ["horizontal", "Liegender Tank"]]), check("Skala anzeigen", "showScale"), number("Hauptintervalle", "majorTicks", 1, 20), number("Unterteilungen", "minorTicks", 0, 10), check("Prozentwert anzeigen", "showPercent"), check("Wellen animieren", "waveAnimation"), number("Wellenhöhe", "waveAmplitude", 0, 15), number("Wellendauer (s)", "waveDuration", .5, 30)]],
  ["thermometer", "Thermometer", "♨", { minValue: -20, maxValue: 50, state: 22, unit: "°C", width: 180, height: 280 }, [select("Skalenseite", "scaleSide", [["left", "Links"], ["right", "Rechts"], ["both", "Beide"]]), check("Skala anzeigen", "showScale"), number("Hauptintervalle", "majorTicks", 1, 20), number("Unterteilungen", "minorTicks", 0, 10)]],
];
registerWidgetSet({ id: "ha-grafik-gauges", label: "HA Grafik – Gauges", widgets: specs.map(([kind, label, icon, defaults, fields]) => ({
  type: `gauge-${kind}`, label, icon, preview: { kind: "plain", lines: [icon] }, searchTerms: [kind, "Gauge", "Messinstrument"],
  defaults: { width: 220, height: 220, entityId: "", state: 50, minValue: 0, maxValue: 100, unit: "%", digits: 0, label: "", showValue: true, showMinMax: true, activeColor: "#29c8b5", trackColor: "#33434c", scaleColor: "#dce6eb", needleColor: "#ef5350", valueColor: "#ffffff", valueSize: 22, trackWidth: 12, roundedCaps: true, levelCount: 3, levelColor1: "#ef5350", levelThreshold1: 30, levelColor2: "#ffca28", levelThreshold2: 70, levelColor3: "#29c8b5", levelThreshold3: 100, sweepAngle: 240, rotation: 0, orientation: "horizontal", cells: 5, charging: false, chargingColor: "#ffca28", waveAnimation: true, waveAmplitude: 3, waveDuration: 3, segments: 0, segmentGap: 2, fromZero: false, showTarget: false, targetValue: 75, targetColor: "#ffca28", showScale: true, majorTicks: 5, minorTicks: 4, compassFormat: "both", showIntercardinal: true, speedUnit: "km/h", displayMode: "bar", needleType: "arrow", bezel: "metal", ringGap: 5, legend: "bottom", ringValue1: 65, ringValue2: 40, ringValue3: 85, ringColor1: "#29c8b5", ringColor2: "#42aee8", ringColor3: "#ffca28", tankShape: "cylinder", scaleSide: "right", backgroundColor: "transparent", borderWidth: 0, padding: 0, ...defaults },
  propertyGroups: [common[0], { label: "Instrument", fields }, common[1], common[2]],
})) });
export function gaugeEntryGroups(widget) {
  if (!widget.type?.startsWith("gauge-")) return [];
  if (widget.type === "gauge-rings") return Array.from({ length: Math.min(8, Math.max(1, Math.trunc(Number(widget.ringCount) || 3))) }, (_, i) => {
    const n = i + 1;
    return { id: `gauge-ring-${n}`, label: `Ring ${n}`, defaultEnabled: true, fields: [{ label: "Home-Assistant-Entität", key: `ringEntityId${n}` }, { label: "Bezeichnung", key: `ringLabel${n}` }, number("Vorschauwert", `ringValue${n}`), number("Mindestwert", `ringMin${n}`), number("Maximalwert", `ringMax${n}`), { label: "Einheit", key: `ringUnit${n}` }, color("Ringfarbe", `ringColor${n}`)] };
  });
  return Array.from({ length: Math.min(10, Math.max(1, Math.trunc(Number(widget.levelCount) || 3))) }, (_, i) => ({ id: `gauge-level-${i + 1}`, label: `Farbstufe ${i + 1}`, css: true, defaultEnabled: true, fields: [number("Bis Wert", `levelThreshold${i + 1}`), color("Farbe", `levelColor${i + 1}`)] }));
}
