import { TABLE_STYLE_GROUPS, tableCount } from "../interactive-table.js";
const number = (label, key, max = 200, min = 0) => ({ label, key, type: "number", min, max });
const color = (label, key) => ({ label, key, type: "color", optionalColor: true });
const check = (label, key, fallback = false) => ({ label, key, type: "checkbox", default: fallback });
const select = (label, key, options) => ({ label, key, type: "select", default: key.startsWith("columnTitleAlign") ? "center" : options[0][0], options: options.map(([value, label]) => ({ value, label })) });
const align = [["left", "Links"], ["center", "Mitte"], ["right", "Rechts"]], direction = [["asc", "Aufsteigend"], ["desc", "Absteigend"]];
export function tableEntryGroups(widget) {
  return [
    ...Array.from({ length: tableCount(widget.countColumns) }, (_, i) => { const n = i + 1; return { id: `interactive-column-${n}`, label: `Spalte [${n}]`, defaultEnabled: true, fields: [
      check("Spalte ausblenden", `columnHidden${n}`), { label: "Schlüssel", key: `columnKey${n}` }, { label: "Formel", key: `columnFormula${n}` }, { label: "Titel", key: `columnTitle${n}` }, number("Spaltenbreite (px, 0 = automatisch)", `columnWidth${n}`, 2000), { label: "Präfix", key: `columnPrefix${n}` }, { label: "Suffix", key: `columnSuffix${n}` }, { label: "Platzhalter", key: `columnPlaceholder${n}` },
      select("Titel ausrichten", `columnTitleAlign${n}`, align), select("Inhalt ausrichten", `columnContentAlign${n}`, align), select("Format", `columnValueFormat${n}`, [["text", "Text"], ["number", "Zahl"], ["boolean", "Boolean"], ["datetime", "Datum/Uhrzeit"], ["image", "Bild"], ["url", "URL"], ["ip", "IP-Adresse"]]),
      number("Dezimalstellen", `columnNumberDecimals${n}`, 10), { label: "Dezimaltrennzeichen", key: `columnDecimalSeparator${n}` }, { label: "Tausendertrennzeichen", key: `columnThousandSeparator${n}` }, color("Boolean-Farbe aktiv", `columnBooleanCheckedColor${n}`), color("Boolean-Farbe inaktiv", `columnBooleanUncheckedColor${n}`),
      select("Datumsformat", `columnDatetimeFormat${n}`, [["datetime", "Datum/Uhrzeit"], ["date", "Datum"], ["time", "Uhrzeit"], ["custom", "Benutzerdefiniert"]]), { label: "Eigenes Datumsformat", key: `columnDatetimeFormatCustom${n}` }, select("Link-Ziel", `columnUrlTarget${n}`, [["_blank", "Neuer Tab"], ["_self", "Gleicher Tab"], ["_parent", "Übergeordnetes Frame"], ["_top", "Oberstes Frame"]]), check("Sortierbar", `sortable${n}`), check("Filter aktivieren", `columnFilterable${n}`),
    ] }; }),
    ...Array.from({ length: tableCount(widget.countDefaultSortColumns, 20) }, (_, i) => ({ id: `table-sort-${i + 1}`, label: `Standardsortierung [${i + 1}]`, defaultEnabled: true, fields: [{ label: "Spaltenschlüssel", key: `defaultSortKey${i + 1}` }, select("Sortierreihenfolge", `defaultSortDir${i + 1}`, direction)] })),
    ...Array.from({ length: tableCount(widget.countRowConditions, 20) }, (_, i) => ({ id: `table-condition-${i + 1}`, label: `Zeilenbedingung [${i + 1}]`, defaultEnabled: true, fields: [{ label: "Spaltenschlüssel oder Index (ab 0)", key: `rowConditionKey${i + 1}` }, select("Vergleichsoperator", `rowConditionOperator${i + 1}`, [["===", "Gleich"], ["!=", "Ungleich"], [">", "Größer"], ["<", "Kleiner"], [">=", "Größer gleich"], ["<=", "Kleiner gleich"]]), { label: "Vergleichswert", key: `rowConditionValue${i + 1}` }, color("Zeilenfarbe", `rowConditionColor${i + 1}`), color("Textfarbe ganze Zeile", `rowConditionValueColor${i + 1}`), color("Textfarbe Bedingungsspalte", `rowConditionColumnValueColor${i + 1}`)] })),
  ];
}
const styleLabels = { backgroundHeader: "Kopfzeilenhintergrund", backgroundOddRow: "Hintergrund ungerade Zeile", backgroundEvenRow: "Hintergrund gerade Zeile", headerHeight: "Kopfzeilenhöhe (px)", columnHeight: "Zeilenhöhe (px)", paginationHeight: "Höhe Seitenleiste (px)", headerBorderWidth: "Kopfzeilenrand (px)", headerBorderColor: "Kopfzeilenrandfarbe", rowBorderWidth: "Zeilenrand (px)", rowBorderColor: "Zeilenrandfarbe", borderRadiusTopLeft: "Oben links", borderRadiusTopRight: "Oben rechts", borderRadiusBottomRight: "Unten rechts", borderRadiusBottomLeft: "Unten links", borderColor: "Randfarbe", borderSizeTop: "Größe oben", borderSizeBottom: "Größe unten", borderSizeLeft: "Größe links", borderSizeRight: "Größe rechts", outerShadowColor: "Äußere Schattenfarbe", outerShadowX: "X-Versatz", outerShadowY: "Y-Versatz", outerShadowBlur: "Unschärfe", outerShadowSize: "Ausdehnung" };
export const interactiveTableDefinition = {
  type: "interactive-table", label: "Tabelle", icon: "▦", searchTerms: ["Table", "JSON Tabelle"],
  defaults: { width: 400, height: 300, entityId: "", entityAttribute: "", tableData: "[]", countColumns: 0, maxRows: 0, showHead: true, pagination: false, rowsPerPage: 10, stickyHeader: false, showSumRow: false, defaultSortOrder: "asc", multiSort: false, countDefaultSortColumns: 0, countRowConditions: 0, headerHeight: 50, columnHeight: 50, paginationHeight: 52, headerBorderWidth: 1, headerBorderColor: "#515151", rowBorderWidth: 1, rowBorderColor: "#515151", borderRadiusTopLeft: 12, borderRadiusTopRight: 0, borderRadiusBottomRight: 12, borderRadiusBottomLeft: 0, borderSizeTop: 0, borderSizeBottom: 0, borderSizeLeft: 0, borderSizeRight: 0, borderStyle: "none", outerShadowColor: "#000000", outerShadowX: 2, outerShadowY: 2, outerShadowBlur: 2, outerShadowSize: 1, backgroundColor: "transparent", borderWidth: 0, radius: 0, padding: 0, cssOverflowX: "visible", cssOverflowY: "visible" },
  propertyGroups: [
    { label: "Allgemein", fields: [{ label: "Home-Assistant-Entität", key: "entityId" }, { label: "HA-Attribut (optional)", key: "entityAttribute" }, { label: "Tabellendaten (JSON, Vorschau / ohne Entität)", key: "tableData", type: "textarea" }, { ...number("Spalten zählen (0 = automatisch)", "countColumns", 50), refreshProperties: true }, number("Max. Zeilen (0 = alle)", "maxRows", 100000), check("Kopf anzeigen", "showHead", true), check("Paginierung", "pagination"), number("Zeilen pro Seite", "rowsPerPage", 500, 1), check("Kopfzeile fixieren", "stickyHeader"), check("Summenzeile markieren", "showSumRow")] },
    { label: "Sortierung", fields: [{ label: "Standard-Sortierspalte", key: "defaultSortColumn" }, select("Standard-Sortierreihenfolge", "defaultSortOrder", direction), check("Mehrspaltensortierung", "multiSort"), { ...number("Anzahl Standardsortierungen", "countDefaultSortColumns", 20), refreshProperties: true }] },
    { label: "Zeilenbedingungen", fields: [{ ...number("Anzahl der Bedingungen", "countRowConditions", 20), refreshProperties: true }] },
    ...TABLE_STYLE_GROUPS.map(([, reference, keys], i) => ({ label: `CSS Tabelle – ${["Darstellung", "Rahmenradius", "Rahmen", "Äußerer Schatten"][i]}`, css: true, defaultEnabled: true, fields: [{ label: "Vom Widget", key: reference, type: "widget", widgetType: "interactive-table" }, ...keys.map(key => key === "borderStyle" ? select("Rahmenstil", key, [["none", "Keiner"], ["solid", "Durchgezogen"], ["dashed", "Gestrichelt"], ["dotted", "Gepunktet"], ["double", "Doppelt"]]) : /Color|background/.test(key) ? color(styleLabels[key], key) : number(styleLabels[key], key, 200, /Shadow(X|Y|Size)$/.test(key) ? -100 : 0))] })),
  ],
};
