const color = (label, key) => ({ label, key, type: "color", optionalColor: true });
const range = (label, key, min = 0, max = 50) => ({ label, key, type: "range", min, max });
const shadow = prefix => [range("X-Versatz", `${prefix}ShadowX`, -50), range("Y-Versatz", `${prefix}ShadowY`, -50), range("Unschärfe", `${prefix}ShadowBlur`), color("Schattenfarbe", `${prefix}ShadowColor`)];
export const radialSliderDefinition = {
  type: "radial-slider", label: "Radialer Schieberegler", icon: "◔", searchTerms: ["Radial Slider", "Drehregler", "Kreisregler"],
  defaults: { width: 200, height: 200, entityId: "", value: 50, minValue: 0, maxValue: 100, step: 1, startAngle: 225, endAngle: 135, showValue: true, showLabel: true, label: "", readOnly: false, trackColor: "#6E6E6E", trackActiveColor: "#5E6B3F", trackWidth: 10, trackShadowX: 2, trackShadowY: 2, trackShadowBlur: 2, trackShadowColor: "#000000", thumbColor: "#455618", thumbSize: 16, thumbShadowX: 2, thumbShadowY: 2, thumbShadowBlur: 2, thumbShadowColor: "#00000080", valueSize: 32, valueColor: "#FFFFFF", labelSize: 14, labelColor: "#C8C8C8", backgroundColor: "transparent", borderWidth: 0, radius: 0, padding: 0, cssOverflowX: "visible", cssOverflowY: "visible" },
  propertyGroups: [
    { label: "Allgemein", fields: [{ label: "Home-Assistant-Entität", key: "entityId" }, { label: "Mindestwert", key: "minValue", type: "number" }, { label: "Maximalwert", key: "maxValue", type: "number" }, { label: "Schritt", key: "step", type: "number", min: .000001 }, range("Startwinkel (°)", "startAngle", 0, 360), range("Endwinkel (°)", "endAngle", 0, 360), { label: "Wert anzeigen", key: "showValue", type: "checkbox" }, { label: "Bezeichnung anzeigen", key: "showLabel", type: "checkbox", refreshProperties: true }, { label: "Bezeichnung", key: "label", showWhen: { key: "showLabel", value: true, default: true } }, { label: "Schreibgeschützt", key: "readOnly", type: "checkbox" }, { label: "Vorschauwert", key: "value", type: "number" }] },
    { label: "CSS Radialregler – Spur", css: true, defaultEnabled: true, fields: [{ label: "Vom Widget", key: "radialTrackFromWidget", type: "widget", widgetType: "radial-slider" }, color("Spurfarbe", "trackColor"), color("Aktive Spurfarbe", "trackActiveColor"), range("Spurbreite (px)", "trackWidth", 1), ...shadow("track")] },
    { label: "CSS Radialregler – Daumen", css: true, defaultEnabled: true, fields: [{ label: "Vom Widget", key: "radialThumbFromWidget", type: "widget", widgetType: "radial-slider" }, color("Daumenfarbe", "thumbColor"), range("Daumengröße (px)", "thumbSize", 1), ...shadow("thumb")] },
    { label: "CSS Radialregler – Wert", css: true, defaultEnabled: true, fields: [range("Wertgröße (px)", "valueSize", 8, 100), color("Wertfarbe", "valueColor"), range("Bezeichnungsgröße (px)", "labelSize", 8, 50), color("Bezeichnungsfarbe", "labelColor")] },
    { label: "Größe und Position", fields: [{ label: "Breite (px)", key: "width", type: "number", min: 32 }, { label: "Höhe (px)", key: "height", type: "number", min: 32 }, { label: "X (px)", key: "x", type: "number" }, { label: "Y (px)", key: "y", type: "number" }] },
  ],
};
