const color = (label, key) => ({ label, key, type: "color", optionalColor: true });
const range = (label, key, min = 0, max = 50) => ({ label, key, type: "range", min, max });
const shadows = prefix => [range("X-Versatz", `${prefix}ShadowX`, -50), range("Y-Versatz", `${prefix}ShadowY`, -50), range("Unschärfe", `${prefix}ShadowBlur`), range("Ausdehnung", `${prefix}ShadowSize`, -50), color("Schattenfarbe", `${prefix}ShadowColor`), color("Schattenfarbe wahr", `${prefix}ShadowColorTrue`)];
export const switchDefinition = {
  type: "styled-switch", label: "Schalten", icon: "●━", searchTerms: ["Switch", "Schalter", "Toggle"],
  defaults: { width: 70, height: 40, entityId: "", state: false, valueFalse: "", valueTrue: "", textFalse: "", textTrue: "", textPosition: "end", trackColorTrue: "#8FA455", trackSize: 12, trackBorderRadius: 100, trackShadowX: 2, trackShadowY: 2, trackShadowBlur: 2, trackShadowSize: 1, trackShadowColor: "#000000", trackShadowColorTrue: "#000000", thumbColorTrue: "#455618", thumbSize: 16, thumbBorderRadius: 100, thumbShadowX: 2, thumbShadowY: 2, thumbShadowBlur: 2, thumbShadowSize: 1, thumbShadowColor: "#00000080", thumbShadowColorTrue: "#00000080", backgroundColor: "transparent", borderWidth: 0, radius: 0, padding: 0, cssOverflowX: "visible", cssOverflowY: "visible" },
  propertyGroups: [
    { label: "Allgemein", fields: [{ label: "Home-Assistant-Entität", key: "entityId" }, { label: "Wert false", key: "valueFalse" }, { label: "Wert true", key: "valueTrue" }, { label: "Text falsch", key: "textFalse", type: "textarea" }, { label: "Text wahr", key: "textTrue", type: "textarea" }, { label: "Textposition", key: "textPosition", type: "select", options: [{ value: "end", label: "Ende" }, { value: "start", label: "Start" }, { value: "top", label: "Oben" }, { value: "bottom", label: "Unten" }] }, { label: "Vorschau-/Testzustand", key: "state" }] },
    { label: "CSS Schalten – Spur", css: true, defaultEnabled: true, fields: [{ label: "Vom Widget", key: "trackFromWidget", type: "widget", widgetType: "styled-switch" }, color("Spurfarbe", "trackColor"), color("Spurfarbe wahr", "trackColorTrue"), range("Spurbreite (px)", "trackSize", 1), range("Spurrundung (%)", "trackBorderRadius", 1, 100), ...shadows("track")] },
    { label: "CSS Schalten – Daumen", css: true, defaultEnabled: true, fields: [{ label: "Vom Widget", key: "thumbFromWidget", type: "widget", widgetType: "styled-switch" }, color("Daumenfarbe", "thumbColor"), color("Daumenfarbe wahr", "thumbColorTrue"), range("Daumengröße (px)", "thumbSize", 1), range("Daumenrundung (%)", "thumbBorderRadius", 1, 100), ...shadows("thumb")] },
    { label: "Größe und Position", fields: [{ label: "Breite (px)", key: "width", type: "number", min: 16 }, { label: "Höhe (px)", key: "height", type: "number", min: 16 }, { label: "X (px)", key: "x", type: "number" }, { label: "Y (px)", key: "y", type: "number" }] },
  ],
};
