import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
const url=process.env.STUDIO_INDUSTRIAL_TEST_URL;
test("housing radius, corner flags, settings color and dragging work in the editor",{skip:!url},async()=>{
  const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE || "playwright");
  const browser=await chromium.launch({headless:true,channel:process.env.STUDIO_THEME_BROWSER || undefined});
  try {
    const context=await browser.newContext({viewport:{width:1600,height:1000}}),page=await context.newPage();
    const packages=await(await context.request.get(new URL("api/widget-packages",url).href)).json();
    const definition=packages.packages.find(p=>p.id==="ugso.industrial").widgets[0];
    let fixture=await(await context.request.get(new URL("api/project",url).href)).json();
    const base={...definition.defaults,type:definition.type,width:128,height:128,housingSnapEnabled:true,housing_top_left:true,housing_top_right:true,housing_bottom_left:true,housing_bottom_right:true,housingSnapAlwaysVisible:true,radius:12};
    fixture.pages[0].widgets=[{...base,id:"left",x:24,y:24},{...base,id:"right",x:170,y:28}];
    fixture.settings={...fixture.settings,autoSave:false,housingSnapColor:"#c792ea"};
    const errors=[];page.on("pageerror",e=>errors.push(e.message));
    await page.route("**/api/project*",async route=>{
      if(route.request().method()==="PUT") fixture=route.request().postDataJSON();
      await route.fulfill({json:fixture});
    });
    await page.goto(url);await page.locator("#left .industrial-gauge").waitFor();
    assert.equal(await page.locator("#left .housing-snap-point").count(),4);
    assert.equal(await page.locator("#left .industrial-gauge").evaluate(el=>getComputedStyle(el).borderRadius),"12px");
    await page.locator("#settings-menu").click();
    await page.locator("#settings-housing-snap-color").fill("#ff8800");await page.locator("#settings-save").click();
    assert.equal(fixture.settings.housingSnapColor,"#ff8800");
    await page.waitForFunction(()=>getComputedStyle(document.querySelector("#left .housing-snap-point")).borderColor==="rgb(255, 136, 0)");
    assert.equal(await page.locator("#left .housing-snap-point").first().evaluate(el=>getComputedStyle(el).borderColor),"rgb(255, 136, 0)");
    const left=await page.locator("#left").boundingBox(),right=await page.locator("#right").boundingBox();
    await page.mouse.move(right.x+right.width/2,right.y+right.height/2);await page.mouse.down();
    await page.mouse.move(left.x+left.width+5+right.width/2,left.y+2+right.height/2,{steps:8});await page.mouse.up();
    const snapped=await page.locator("#right").boundingBox();
    assert.ok(Math.abs(snapped.x-left.x-left.width-2)<.1);assert.ok(Math.abs(snapped.y-left.y)<.1);
    assert.ok((await page.locator("#properties").textContent()).includes("Gehäuse-Snappunkte"));
    await page.locator("#right .industrial-gauge").click();
    await page.locator("#properties details").evaluateAll(items=>items.forEach(item=>item.open=true));
    const lock=page.locator("#properties [data-property-key='aspectRatio1to1']");
    const screws=page.locator("#properties [data-property-key='industrialScrewsEnabled']"),style=page.locator("#properties [data-property-key='industrialStyle']");
    assert.equal(await screws.isChecked(),true);
    await screws.uncheck();
    assert.equal(await page.locator("#right .industrial-gauge circle[r='4']").count(),0);
    await style.uncheck();
    await page.locator("#properties details").evaluateAll(items=>items.forEach(item=>item.open=true));
    assert.equal(await screws.isDisabled(),true);
    await style.check();
    await page.locator("#properties details").evaluateAll(items=>items.forEach(item=>item.open=true));
    assert.equal(await screws.isChecked(),true);
    assert.equal(await page.locator("#right .industrial-gauge circle[r='4']").count(),4);
    assert.ok((await page.locator("#properties").textContent()).includes("Wertanzeige"));
    await page.locator("#properties [data-property-key='showValue']").check();
    await page.locator("#properties [data-property-key='valuePosition']").selectOption("center");
    await page.locator("#properties [data-property-key='valueFontSize']").fill("18");
    await page.locator("#properties [data-property-key='valueColor']").evaluate(el=>{el.value="#ffcc00";el.dispatchEvent(new Event("input",{bubbles:true}));});
    assert.equal(await page.locator("#right .industrial-gauge text").getAttribute("y"),"64");
    assert.equal(await page.locator("#right .industrial-gauge text").getAttribute("fill"),"#ffcc00");
    await page.locator("#properties [data-property-key='valuePosition']").selectOption("bottom");
    assert.equal(await page.locator("#right .industrial-gauge text").getAttribute("y"),"110");
    assert.equal(await page.locator("#properties [data-property-key='industrialFrameWidth']").isDisabled(),true);
    await page.locator("#properties [data-property-key='industrialFrameWidthEnabled']").check();
    await page.locator("#properties details").evaluateAll(items=>items.forEach(item=>item.open=true));
    await page.locator("#properties [data-property-key='industrialFrameWidth']").fill("5");
    await page.locator("#properties [data-property-key='industrialFrameColor']").evaluate(el=>{el.value="#ffcc00";el.dispatchEvent(new Event("input",{bubbles:true}));});
    assert.equal(await page.locator("#right .industrial-gauge").evaluate(el=>getComputedStyle(el).borderTopWidth),"5px");
    assert.equal(await page.locator("#right .industrial-gauge").evaluate(el=>getComputedStyle(el).borderTopColor),"rgb(255, 204, 0)");
    await page.locator("#properties [data-property-key='industrialFrameWidthEnabled']").uncheck();
    assert.equal(await page.locator("#right .industrial-gauge").evaluate(el=>getComputedStyle(el).borderTopWidth),"2px");
    await page.locator("#properties details").evaluateAll(items=>items.forEach(item=>item.open=true));
    assert.equal(await page.locator("#properties [data-property-key='industrialFrameWidth']").inputValue(),"5");
    await page.locator("#properties [data-property-key='industrialFrameWidthEnabled']").check();
    await page.locator("#properties details").evaluateAll(items=>items.forEach(item=>item.open=true));
    assert.equal(await page.locator("#right .industrial-gauge").evaluate(el=>getComputedStyle(el).borderTopWidth),"5px");
    const width=page.locator("#properties [data-property-key='width']").first(),height=page.locator("#properties [data-property-key='height']").first();
    assert.equal(await lock.isChecked(),true);
    await width.fill("192");await width.press("Tab");assert.equal(await height.inputValue(),"192");
    await height.fill("160");await height.press("Tab");assert.equal(await width.inputValue(),"160");
    const handle=page.locator("#right .resize-handle[data-direction='se']"),handleBox=await handle.boundingBox();
    await page.mouse.move(handleBox.x+handleBox.width/2,handleBox.y+handleBox.height/2);await page.mouse.down();await page.mouse.move(handleBox.x+handleBox.width/2+24,handleBox.y+handleBox.height/2+10);await page.mouse.up();
    assert.equal(await width.inputValue(),await height.inputValue());assert.equal(await width.inputValue(),"184");
    await lock.uncheck();
    await page.locator("#properties details").evaluateAll(items=>items.forEach(item=>item.open=true));
    await width.fill("224");await width.press("Tab");assert.equal(await height.inputValue(),"184");
    const independent=await page.locator("#right").boundingBox();assert.equal(independent.width,224);assert.equal(independent.height,184);
    await lock.check();
    assert.equal(await width.inputValue(),"224");assert.equal(await height.inputValue(),"224");
    await page.goto(new URL("runtime",url).href);await page.locator("#left .industrial-gauge").waitFor();
    assert.equal(await page.locator(".housing-snap-point").count(),0);
    assert.deepEqual(errors,[]);
  }finally{await browser.close();}
});
